# Leave this out if using subdirectories in path. It causes issues with toCSS.
# baseURL: 'http://example.org/'
relativeURLs: true
languageCode: en
title: Colin Dickens Resume
theme: hugo-devresume-theme
params:
  author: CowboySmall
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  primaryColor: '#54B689'
  textPrimaryColor: '#292929'
  profile:
    enable: true
    name: Colin Dickens
    tagline: Student
    avatar: avatar.JPG
  contact:
    enable: true
    location: Alabama
    list:
      # - icon: fas fa-phone-square
      # url: 'tel:#'
      # text: 0123 4567 87
      - icon: fas fa-envelope-square
        url: 'mailto:#'
        text: cdickens0201@nacc.edu
      - icon: fas fa-globe
        url: '#'
        text: https://www.linkedin.com/in/colin-dickens-/
  skills:
    enable: true
    list:
      - title: Technical
        items:
          - details: JavaScript/Angular/React/Vue
          - details: Python/Ruby/PHP
          - details: Node.js/ASP.NET
          - details: PostgreSQL/MySQL
          - details: Object-oriented design
          - details: Design and implement database structures
          - details: Lead and deliver complex software systems
      - title: Professional
        items:
          - details: Effective communication
          - details: Team player
          - details: Strong problem solver
          - details: Good time management
  education:
    enable: true
    list:
      - degree: MIS
        university: University of Alabama
        dates: 2018 - 2022
  awards:
    enable: false
    list:
      - name: Award Lorem Ipsum
        body: Microsoft lorem ipsum
        date: '2019'
      - name: Award Donec Sodales
        body: Oracle Aenean
        date: '2017'
  languages:
    enable: false
    list:
      - name: English
        level: Native
      - name: Spanish
        level: Professional
  interests:
    enable: true
    list:
      - name: Skiing
      - name: Programing
      - name: Sports
      - name: Travelling
  summary:
    enable: true
    text: >-
      Hello, I go to the University of Alabama. I'm majoring in MIS with a minor in computing technologies. I have two brothers. I played football lacrosse and hockey in high school. I enjoy golfing. I also like trying different foods.
  experience:
    enable: true
    list:
      - title: Student
        dates: 2018 - Present
        company: University of Alabama
        details: >-
          Took MIS programing classes learning different languages.
        items:
          - details: C#
          - details: Java
          - details: Java Script
  projects:
    enable: false
    list:
      - title: Project Lorem Ipsum
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Lorem ipsum dolor sit
          amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
          Aenean massa. Cum sociis natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus.
      - title: Project Sed Fringilla
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
      - title: Project Praesent
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
  information:
    enable: false
    list:
      - title: Papers
        items:
          - details: 2018 · Lorem Ipsum
          - details: 2016 · Sed Fringilla
      - title: Interests
        details: 'Climbing, Snowboarding, Photography, Travelling'
  social:
    enable: true
    list:
      - icon: fab fa-github-square
        url: //github.com/username
        title: username
        # - icon: fab fa-linkedin
        # url: //linkedin.com/in/username
        # title: username
        # - icon: fab fa-twitter-square
        # url: //twitter.com/username
        # title: '@username'
  footer:
    copyright: Colin Dickens 2020